title: sudo Owen Williams
description: “Every morning starts like this, graphic sex talk. Thankfully, I’m able to tune most of it out. When people talk like this, they’re either insecure or they’re full of shame.” — Elliot Alderson, Mr. Robot, season_3.0: eps3.4_runtime-error.r00
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
