title: sudo Owen Williams
description: “When you delete something, you’re making a choice to destroy it. To never see it again.” — Elliot Alderson, Mr. Robot, season_3.0: eps3.7_dont-delete-me.ko
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
